version: '3.8'

services:
  gunicorn:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mariadb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
      DB_PORT: "3306"
    container_name: gunicorn-app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: nginx
    depends_on:
      - gunicorn

  mariadb:
    image: mariadb:10.6.20
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      #- ./mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - mariadb_data:/var/lib/mysql
    ports:
      - "3336:3306"
    depends_on:
      - gunicorn

volumes:
  mariadb_data: