GRANT ALL PRIVILEGES ON mydatabase.* TO 'myuser'@'%' IDENTIFIED BY 'mypassword';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'myrootpassword' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS quotation (
  id INT AUTO_INCREMENT PRIMARY KEY,
  text VARCHAR(255) NOT NULL,
  author VARCHAR(100) NOT NULL,
  category VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_text_author (text, author)
);

INSERT IGNORE INTO quotation (text, author, category) VALUES
('The best way to get started is to quit talking and begin doing.', 'Walt Disney', 'Action'),
('Don’t let yesterday take up too much of today.', 'Will Rogers', 'Motivation'),
('It’s not whether you get knocked down, it’s whether you get up.', 'Vince Lombardi', 'Resilience'),
('If you are working on something exciting, it will keep you motivated.', 'Steve Jobs', 'Inspiration'),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'Success'),
('The harder you work for something, the greater you’ll feel when you achieve it.', 'Anonymous', 'Effort'),
('Dream bigger. Do bigger.', 'Anonymous', 'Dream'),
('Don’t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'Persistence'),
('Great things never come from comfort zones.', 'Anonymous', 'Challenge'),
('Push yourself, because no one else is going to do it for you.', 'Anonymous', 'Discipline'),
('Sometimes we’re tested not to show our weaknesses, but to discover our strengths.', 'Anonymous', 'Strength'),
('The key to success is to focus on goals, not obstacles.', 'Anonymous', 'Focus'),
('Believe you can and you’re halfway there.', 'Theodore Roosevelt', 'Belief'),
('Fall seven times, stand up eight.', 'Japanese Proverb', 'Perseverance'),
('You are never too old to set another goal or to dream a new dream.', 'C.S. Lewis', 'Dream'),
('If you can dream it, you can do it.', 'Walt Disney', 'Dream'),
('Hardships often prepare ordinary people for an extraordinary destiny.', 'C.S. Lewis', 'Destiny'),
('Don’t wait for opportunity. Create it.', 'George Bernard Shaw', 'Initiative'),
('Little things make big days.', 'Isabel Marant', 'Details'),
('Success doesn’t just find you. You have to go out and get it.', 'Anonymous', 'Success'),
('The only limit to our realization of tomorrow is our doubts of today.', 'Franklin D. Roosevelt', 'Hope'),
('Act as if what you do makes a difference. It does.', 'William James', 'Impact'),
('Happiness is not by chance, but by choice.', 'Jim Rohn', 'Happiness'),
('You do not find the happy life. You make it.', 'Camilla Eyring Kimball', 'Happiness'),
('Stay foolish to stay sane.', 'Maxime Lagacé', 'Creativity'),
('Try to be a rainbow in someone’s cloud.', 'Maya Angelou', 'Kindness'),
('What we think, we become.', 'Buddha', 'Mindset'),
('Be so good they can’t ignore you.', 'Steve Martin', 'Excellence'),
('Impossible is for the unwilling.', 'John Keats', 'Determination'),
('No pressure, no diamonds.', 'Thomas Carlyle', 'Challenge'),
('Everything you can imagine is real.', 'Pablo Picasso', 'Imagination'),
('I never dream of success. I work for it.', 'Estée Lauder', 'Work'),
('What defines us is how well we rise after falling.', 'Lionel from Maid in Manhattan', 'Resilience'),
('Believe in yourself and all that you are.', 'Christian D. Larson', 'Confidence'),
('Do one thing every day that scares you.', 'Eleanor Roosevelt', 'Courage'),
('Your passion is waiting for your courage to catch up.', 'Isabelle Lafleche', 'Passion'),
('Magic is believing in yourself.', 'Johann Wolfgang von Goethe', 'Belief'),
('If something is important enough, even if the odds are against you, you should still do it.', 'Elon Musk', 'Motivation'),
('Hold the vision, trust the process.', 'Anonymous', 'Vision'),
('Don’t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'Ambition'),
('Go the extra mile. It’s never crowded.', 'Wayne Dyer', 'Effort'),
('Do what you can, with what you have, where you are.', 'Theodore Roosevelt', 'Action'),
('You don’t need to see the whole staircase, just take the first step.', 'Martin Luther King Jr.', 'Faith'),
('Start where you are. Use what you have. Do what you can.', 'Arthur Ashe', 'Resourcefulness'),
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Work'),
('Strive not to be a success, but rather to be of value.', 'Albert Einstein', 'Purpose'),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'Success'),
('There is no traffic jam along the extra mile.', 'Roger Staubach', 'Persistence'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Resilience');